### ISSUE TITLE
Enable remote debugging option

### ISSUE THREAD

**Issue by jonnyscholes** [lsrom/webview-tester#1]
I'm unsure if Google Play allows this when adding the app to their app store, but it would be really useful if this app were able to have remote debugging enabled.

More info here:
https://developers.google.com/web/tools/chrome-devtools/remote-debugging/webviews

p.s. Very useful app - thanks!

**Comment by lsrom** [comment]
Hi, I added what you wanted, check out new release either here or on Google Play. I'm not sure if it does what you want though, so feel free to contact me again if it isn't working. For now, I'm closing this.

**Comment by jonnyscholes** [comment]
Thanks @lsrom ! That feature is so incredibly useful. None of the other webview tester apps on Android do this either. Thanks for the speedy implementation and release! Legend!
